name: test-build
on:
  pull_request:
  push:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Update changelog"
        run: |
          set -ex
          OLD_VERSION=$(dpkg-parsechangelog -SVersion)
          SOURCE=$(dpkg-parsechangelog -SSource)
          cat > debian/changelog <<EOT
          ${SOURCE} (${OLD_VERSION}+autobuild${GITHUB_RUN_NUMBER}) UNRELEASED; urgency=medium

            * Automated Build

           -- Automated Build <builder@localhost>  $(date -R)
          EOT
      - uses: jtdor/build-deb-action@v1
      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: deb
          if-no-files-found: error
          path: |
            debian/artifacts/*

  zsh-refcard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install texlive
        run: |
          set -ex
          sudo apt update
          sudo apt install -y texlive-fonts-recommended texlive-latex-recommended
      - name: Build grml-zsh-refcard
        run: |
          set -ex
          git clone --depth 1 https://github.com/grml/grml-gen-zshrefcard
          cd grml-gen-zshrefcard
          ./genrefcard.pl < ../etc/zsh/zshrc > grml-zsh-refcard.tex
          pdflatex grml-zsh-refcard.tex
      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: zsh-refcard
          if-no-files-found: error
          path: |
            grml-gen-zshrefcard/grml-zsh-refcard.tex
            grml-gen-zshrefcard/grml-zsh-refcard.pdf
